// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication4.DAL;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication4.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Jan",
                            HireDate = new DateOnly(2020, 1, 1),
                            LastName = "Nowak"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Anna",
                            HireDate = new DateOnly(2020, 1, 1),
                            LastName = "Kowalska"
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.Nursery", b =>
                {
                    b.Property<int>("NurseryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NurseryId"));

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NurseryId");

                    b.ToTable("Nurseries");

                    b.HasData(
                        new
                        {
                            NurseryId = 1,
                            EstablishedDate = new DateOnly(1990, 5, 15),
                            Name = "szkola lesna 1"
                        },
                        new
                        {
                            NurseryId = 2,
                            EstablishedDate = new DateOnly(1995, 3, 10),
                            Name = "szkola lesna 2"
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.Responsible", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId", "BatchId");

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("WebApplication4.Models.Seedling_Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<int>("NurseryId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReadyDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SownDate")
                        .HasColumnType("date");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.ToTable("SeedlingBatches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            NurseryId = 1,
                            Quantity = 1000,
                            SownDate = new DateOnly(2023, 4, 1),
                            SpeciesId = 1
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.Tree_Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("GrowthTimeInYears")
                        .HasColumnType("integer");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpeciesId");

                    b.ToTable("TreeSpecies");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            GrowthTimeInYears = 30,
                            LatinName = "Quercus robur"
                        },
                        new
                        {
                            SpeciesId = 2,
                            GrowthTimeInYears = 20,
                            LatinName = "Pinus sylvestris"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
